-- Create dev_resources table
create table if not exists public.dev_resources (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  url text not null,
  github_url text,
  category text,
  tags text[],
  language text,
  license text,
  logo_url text,
  is_featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.dev_resources enable row level security;

-- Policy: Allow public read access
create policy "Allow public read access dev_resources"
  on public.dev_resources
  for select
  using (true);

-- Policy: Allow authenticated users to do EVERYTHING
create policy "Allow full access for authenticated users dev_resources"
  on public.dev_resources
  for all
  to authenticated
  using (true)
  with check (true);

-- Policy: Allow public insert (optional, if we want public submissions later, but for now maybe keep it restricted or same as others)
-- Let's allow public insert for consistency with other tables if we add a submit modal later.
create policy "Allow public insert dev_resources"
  on public.dev_resources
  for insert
  with check (true);
