create table public.news (
  id text primary key,
  title text not null,
  summary text,
  detail text,
  link text unique,
  tags text[],
  date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table public.ai_tools (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  link text not null,
  category text,
  tags text[],
  submitted_at timestamp with time zone default timezone('utc'::text, now()),
  approved boolean default false
);

alter table public.ai_tools enable row level security;
create policy "Allow public insert" on public.ai_tools for insert with check (true);
ALTER TABLE public.ai_tools ADD CONSTRAINT ai_tools_link_key UNIQUE (link);

-- Create ai_prompts table
create table if not exists public.ai_prompts (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  content text not null,
  category text not null,
  tags text[],
  image_url text,
  author text,
  approved boolean default false,
  version integer default 1,
  is_deleted boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.ai_prompts enable row level security;

-- Create Policy: Allow read access to everyone
-- (In a real app you might filter by approved=true, but for now we allow reading all or handle filtering in client)
create policy "Allow public read access"
  on public.ai_prompts
  for select
  using (true);

-- Create Policy: Allow insert access to everyone (for submissions)
create policy "Allow public insert access"
  on public.ai_prompts
  for insert
  with check (true);
