-- Update RLS policies for Admin Dashboard security

-- Helper function to check if user is authenticated
-- (Supabase auth.role() returns 'authenticated' for logged in users)

-- 1. AI Tools Table
ALTER TABLE public.ai_tools ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to do EVERYTHING (Select, Insert, Update, Delete)
CREATE POLICY "Allow full access for authenticated users ai_tools"
ON public.ai_tools
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Ensure public can still read (Select)
DROP POLICY IF EXISTS "Allow public read access ai_tools" ON public.ai_tools;
CREATE POLICY "Allow public read access ai_tools"
ON public.ai_tools FOR SELECT USING (true);

-- Ensure public can still insert (Submit)
DROP POLICY IF EXISTS "Allow public insert ai_tools" ON public.ai_tools; -- Drop old name if exists
DROP POLICY IF EXISTS "Allow public insert" ON public.ai_tools;
CREATE POLICY "Allow public insert ai_tools"
ON public.ai_tools FOR INSERT WITH CHECK (true);


-- 2. Design Resources Table
ALTER TABLE public.design_resources ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to do EVERYTHING
CREATE POLICY "Allow full access for authenticated users design_resources"
ON public.design_resources
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Ensure public can still read
DROP POLICY IF EXISTS "Allow public read access design_resources" ON public.design_resources;
CREATE POLICY "Allow public read access design_resources"
ON public.design_resources FOR SELECT USING (true);

-- Ensure public can still insert
DROP POLICY IF EXISTS "Allow public insert design_resources" ON public.design_resources;
CREATE POLICY "Allow public insert design_resources"
ON public.design_resources FOR INSERT WITH CHECK (true);


-- 3. AI Prompts Table
ALTER TABLE public.ai_prompts ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to do EVERYTHING
CREATE POLICY "Allow full access for authenticated users ai_prompts"
ON public.ai_prompts
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Ensure public can still read
DROP POLICY IF EXISTS "Allow public read access" ON public.ai_prompts;
CREATE POLICY "Allow public read access ai_prompts"
ON public.ai_prompts FOR SELECT USING (true);

-- Ensure public can still insert
DROP POLICY IF EXISTS "Allow public insert access" ON public.ai_prompts;
CREATE POLICY "Allow public insert ai_prompts"
ON public.ai_prompts FOR INSERT WITH CHECK (true);


-- 4. News Table
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to do EVERYTHING
CREATE POLICY "Allow full access for authenticated users news"
ON public.news
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Ensure public can still read
DROP POLICY IF EXISTS "Allow public read access news" ON public.news;
CREATE POLICY "Allow public read access news"
ON public.news FOR SELECT USING (true);

-- News is typically generated by script, which uses service role key (bypasses RLS),
-- but if we want to edit via Admin Dashboard (authenticated user), we need the policy above.
